# **SQL on python**

## **1.환경준비**

In [ ]:
import pandas as pd
import sqlite3

import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

## **2.DB 작업**

### (1) DB 생성 및 연결

* 데이터베이스 연결
    * 폴더는 미리 생성
    * 해당 파일이 없으면 새로 생성, 있으면 연결

In [ ]:
path = './db_chatlog/db_chatlog.db'
conn = sqlite3.connect(path)

### (2) 테이블 생성

In [ ]:
# 커서 객체 생성
cursor = conn.cursor()

# test 테이블 생성
cursor.execute('''
CREATE TABLE IF NOT EXISTS test (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    age INTEGER NOT NULL
)
''')

# 변경사항 커밋 (저장)
conn.commit()

# 연결 종료
conn.close()

### (3) DB 작업 절차

* 1. 커서 활용 : 대부분의 SQL 작업 가능
    * ① 연결
    * ② 커서 선언
    * ③ 작업 : sql
    * ④ 커밋(수정작업 저장)
    * ⑤ 연결종료

* 2. pandas 함수 활용 : 주로 insert, update, delete, select, create table & insert
    * ① 연결
    * ② 작업 : pandas 함수 이용
    * ③ 연결종료

#### 1) insert

In [ ]:
# ① 연결
conn = sqlite3.connect(path)

# ② 작업 : to_sql
data = pd.DataFrame({'name': ['Alice', 'Bob', 'Charlie', 'David'], 'age': [30, 25, 35, 40]})
data.to_sql('test', conn, if_exists='append', index=False) # test 테이블이 있으면 insert, 없으면 생성

# ③ 연결 종료
conn.close()

#### 2) Select

In [ ]:
# ① 연결
conn = sqlite3.connect(path)

# ② 작업 : select
df = pd.read_sql('SELECT * FROM test', conn)
display(df)

# ③ 연결 종료
conn.close()

#### 3) Drop

* 커서로만 작업 가능

In [ ]:
# ① 연결
conn = sqlite3.connect(path)

# ② 커서 선언
cursor = conn.cursor()

# ③ 작업 : 테이블 삭제
cursor.execute('DROP TABLE IF EXISTS test')

# ④ 커밋(수정작업 저장)
conn.commit()

# ⑤ 연결종료
conn.close()

## 3.실습

* 테이블 추가 : log

        CREATE TABLE IF NOT EXISTS log (
            id INTEGER PRIMARY KEY,
            datetime TEXT NOT NULL,
            score REAL NOT NULL
        )

* 데이터 1 건 입력
    * datetime : 현재 시스템 시간 yyyy-mm-dd hh:mi:ss
    * score : 0.3512

In [ ]:
conn = sqlite3.connect(path)

# 커서 객체 생성
cursor = conn.cursor()

# test 테이블 생성
cursor.execute('''
CREATE TABLE IF NOT EXISTS log (
    id INTEGER PRIMARY KEY,
    datetime TEXT NOT NULL,
    score REAL NOT NULL
)
''')

# 변경사항 커밋 (저장)
conn.commit()

# 연결 종료
conn.close()

In [ ]:
from datetime import datetime

# 현재 시간
dt = datetime.now()
dt = dt.strftime('%Y-%m-%d %H:%M:%S')

score = 0.3512

# ① 연결
conn = sqlite3.connect(path)

# ② 작업 : to_sql
data = pd.DataFrame({'datetime': [dt], 'score': [score]})
data.to_sql('log', conn, if_exists='append', index=False) # test 테이블이 있으면 insert, 없으면 생성

# 확인
df = pd.read_sql('SELECT * FROM log', conn)
display(df)

# ③ 연결 종료
conn.close()